name: Build & Deploy to Ubuntu

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted 

    env:
      PORT: 8080

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t be-my-coin:latest .

      - name: Stop & remove old container (if exists)
        run: |
          docker rm -f be-my-coin || true

      - name: Run new container
        run: |
          docker run -d \
            --name be-my-coin \
            -p 8080:8080 \
            -e PORT=${{ env.PORT }} \
            be-my-coin:latest
