name: Build & Deploy to Ubuntu

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    env:
      PORT: 8080

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t be-my-coin:latest .

      - name: Stop & remove old container (if exists)
        run: |
          docker rm -f be-my-coin || true

      - name: Run new container
        run: |
          docker run -d \
            --name be-my-coin \
            -p 8080:8080 \
            -e PORT=${{ env.PORT }} \
            -e HOST=${{ secrets.DB_HOST }} \
            -e USER_DB=${{ secrets.DB_USER }} \
            -e PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e DATABASE_NAME=${{ secrets.DB_NAME }} \
            -e PASSWORD_SECRET=${{ secrets.PASSWORD_SECRET }} \
            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
            be-my-coin:latest
